services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ../hte-location-ms/migrations/locations.sql:/docker-entrypoint-initdb.d/locations.sql
  device_update_dispatcher:
    build: ../hte-device-update-dispatcher
    ports:
      - "9090:8080"
    links:
      - "redis"
    environment:
      - REDIS_HOST=redis:6379
  device_update_consumer:
    build: ../hte-device-update-consumer
    links:
      - "redis"
      - "location_ms"
    environment:
      - REDIS_HOST=redis:6379
      - API_LOCATION_HOST=http://location_ms:8080
  location_ms:
    build: ../hte-location-ms
    ports:
      - "9091:8080"
    links:
      - "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432