global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'device_update_dispatcher'
    static_configs:
      - targets: [ 'device_update_dispatcher:8081' ]
  - job_name: 'device_update_consumer'
    static_configs:
      - targets: [ 'device_update_consumer:8081' ]
  - job_name: 'location_ms'
    static_configs:
      - targets: ['location_ms:8081']
  - job_name: 'status_ms'
    static_configs:
      - targets: [ 'status_ms:8081' ]
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
