version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    networks:
      dznetwork:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../../hte-danger-zone-ms/migrations/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      dznetwork:
  danger-zone-ms:
    build: ../../hte-danger-zone-ms
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_DANGER_ZONES_TABLE=${POSTGRES_DANGER_ZONES_TABLE}
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CHANNEL_CREATE_ZONE=${REDIS_CHANNEL_CREATE_ZONE}
      - REDIS_CHANNEL_DELETE_ZONE=${REDIS_CHANNEL_DELETE_ZONE}
    depends_on:
      - redis
      - postgres
    restart: always
    networks:
      dznetwork:
  danger-zone-job:
    build: ../../hte-danger-zone-job
    environment:
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CHANNEL_CREATE_ZONE=${REDIS_CHANNEL_CREATE_ZONE}
      - REDIS_CHANNEL_DELETE_ZONE=${REDIS_CHANNEL_DELETE_ZONE}
      - REDIS_CHANNEL_GEOLOC=${REDIS_CHANNEL_GEOLOC}
      - REDIS_KEY_DANGER_ZONE=${REDIS_KEY_DANGER_ZONE}
      - REDIS_QUEUE_ALARMS=${REDIS_QUEUE_ALARMS}
      - API_DANGERZONE_HOST=http://danger-zone-ms:8080
    depends_on:
      - redis
      - danger-zone-ms
    restart: always
    networks:
      dznetwork:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    networks:
      dznetwork:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      dznetwork:
networks:
  dznetwork: